"""empty message

Revision ID: 25113c1e086e
Revises: 741672a7fb3d
Create Date: 2021-12-27 13:49:28.852334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25113c1e086e'
down_revision = '741672a7fb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors', 'status')
    # ### end Alembic commands ###
