"""empty message

Revision ID: 73d0e28725c1
Revises: 2da54843998f
Create Date: 2021-12-15 13:58:32.251410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d0e28725c1'
down_revision = '2da54843998f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('name', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'scenario', ['name'])
    op.drop_column('scenario', 'username')
    op.add_column('user', sa.Column('username', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.add_column('scenario', sa.Column('username', sa.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'scenario', type_='unique')
    op.drop_column('scenario', 'name')
    # ### end Alembic commands ###
