"""empty message

Revision ID: 741672a7fb3d
Revises: 
Create Date: 2021-12-22 12:58:33.398495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741672a7fb3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('credit_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_type_id'], ['credit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('credit_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_balance', sa.BigInteger(), nullable=False),
    sa.Column('new_balance', sa.BigInteger(), nullable=False),
    sa.Column('credit_amount', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('Scenario_id', sa.Integer(), nullable=False),
    sa.Column('Schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_balances')
    op.drop_table('user_role_association')
    op.drop_table('sponsors')
    op.drop_table('users')
    op.drop_table('scenarios')
    op.drop_table('roles')
    op.drop_table('credit_types')
    # ### end Alembic commands ###
