"""empty message

Revision ID: a0a78ad53f8d
Revises: a4bfefecd5e3
Create Date: 2022-01-10 15:45:48.592307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a78ad53f8d'
down_revision = 'a4bfefecd5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Locations', sa.Column('distance_lat_long', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Locations', 'distance_lat_long')
    # ### end Alembic commands ###
