"""empty message

Revision ID: a4bfefecd5e3
Revises: 
Create Date: 2022-01-10 14:03:18.249141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bfefecd5e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('credit_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_type_id'], ['credit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('credit_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_balance', sa.BigInteger(), nullable=False),
    sa.Column('new_balance', sa.BigInteger(), nullable=False),
    sa.Column('credit_amount', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('Scenario_id', sa.Integer(), nullable=False),
    sa.Column('Schedule_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_credit_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=15), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('sender_number', sa.String(length=15), nullable=False),
    sa.Column('sender_user', sa.String(length=20), nullable=False),
    sa.Column('sender_pass', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('delay', sa.BigInteger(), nullable=False),
    sa.Column('location_limit', sa.Integer(), nullable=False),
    sa.Column('last_modify_date', sa.DateTime(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('notification_type_id', sa.Integer(), nullable=True),
    sa.Column('scenario_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.ForeignKeyConstraint(['scenario_type_id'], ['scenario_types.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.String(length=60), nullable=True),
    sa.Column('lac_id', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('province', sa.String(length=60), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('location_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_type_id'], ['Location_types.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ran_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('Message', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senario_calender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.Column('repeat', sa.String(length=20), nullable=False),
    sa.Column('from_time', sa.Time(), nullable=False),
    sa.Column('to_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('province', sa.String(length=60), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affected_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('Message', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('ran_scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ran_scenario_id'], ['ran_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affected_users')
    op.drop_table('senario_calender')
    op.drop_table('ran_schedules')
    op.drop_table('Locations')
    op.drop_table('scenarios')
    op.drop_table('credit_balances')
    op.drop_table('user_role_association')
    op.drop_table('sponsors')
    op.drop_table('users')
    op.drop_table('scenario_types')
    op.drop_table('roles')
    op.drop_table('notification_types')
    op.drop_table('credit_types')
    op.drop_table('Location_types')
    # ### end Alembic commands ###
