"""empty message

Revision ID: b65b9ddde5fd
Revises: a0a78ad53f8d
Create Date: 2022-01-10 16:10:21.728597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65b9ddde5fd'
down_revision = 'a0a78ad53f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Locations', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('Locations', sa.Column('Lat_long_distance', sa.String(length=200), nullable=True))
    op.drop_column('Locations', 'distance_lat_long')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Locations', sa.Column('distance_lat_long', sa.INTEGER(), nullable=True))
    op.drop_column('Locations', 'Lat_long_distance')
    op.drop_column('Locations', 'distance')
    # ### end Alembic commands ###
